name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  build_skim:
    runs-on: ubuntu-latest
    COMPILER: $(root-config --cxx)
    outputs:
      output1: skim
    steps:
      - run: $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx
      
